### ISSUE TITLE
Spreading partial Record to create a new Record does not forward types correctly

### ISSUE THREAD

**Issue by NavaceSystem** [runtypes/runtypes#278]
I'm looking to have a partial version of a type with only id field as required.

```javascript
// this is base dto representing a valid object
const dto = t.Record({
  id: t.String,
  name: t.String
})
// this is the dto used for updating, all fields are optional except for id
const partialDto = t.Record({
  ...dto.asParial().fields,
  id: t.String
})
```
**Expected:**
`{ id: string, name?: string | undefined}`
**Actual**:
`{ id: string, name: string }`

I've also tried it the other way around but in this case the id isn't being set as required.
```javascript
const partialDto = dto.asParial().extend({ id: t.String })
```
**Expected:**
`{ id: string, name?: string | undefined}`
**Actual**:
`{ id?: string | undefined, name?: string | undefined }`

**Comment by yuhr** [comment]
The most succinct way to achieve this is `Intersect`.

```ts
const partialDto = dto.asPartial().And(t.Record({ id: String }));
```

But this result in a hard-to-read static type such as:

```ts
{
    id?: string | undefined;
    name?: string | undefined;
} & {
    id: string;
}
```

Other ways are too complex to write here, so we want to support this use case. Personally I'd prefer your second example,

> ```
> const partialDto = dto.asParial().extend({ id: t.String })
> ```

This way users should expect as you expected. To avoid lacking of readability, it must be context-insensitive like this: if one wants to extend with optional properties then use `Optional` for them, otherwise it's not treated as optional. This would be a breaking change though.

**Comment by NavaceSystem** [comment]
Got it, thanks.

**Comment by yuhr** [comment]
Both cases should now work as intended. Please wait for the next release.
